version: '3'

services:

  kaldi-logmel:
    build: ./kaldi_logmel/
    volumes:
      - tmp-volume:/tmp/
    container_name: kaldi-logmel

  gentle-xmlrpc:
    build: ./gentle_xmlrpc/
    volumes:
      - tmp-volume:/tmp/
    container_name: gentle-xmlrpc

  punct-segment-xmlrpc:
    build: ./punct_segment_xmlrpc/
    container_name: punct-segment-xmlrpc

  tensorflow-serving-vad:
    image: tensorflow/serving:latest
    restart: unless-stopped
    volumes:
      - ./tensorflow_serving_vad:/models
    command: --model_config_file=/models/models.cfg
    container_name: tensorflow-serving-vad

  autotimecode-api:
    build: ./autotimecode_api/
    container_name: autotimecode-api
    environment:
      - MONGO_URL
      - CELERY_BROKER_URL
    ports:
      - 5055:5055

  autotimecode-worker:
    build: ./autotimecode_worker/
    container_name: autotimecode-worker
    volumes:
      - tmp-volume:/tmp/
    environment:
      - MONGO_URL
      - CELERY_BROKER_URL

  autotimecode-fe:
    build: ./autotimecode_fe/
    container_name: autotimecode-fe
    ports:
      - 5056:800

volumes:
  tmp-volume:
    driver: local
